Task/bam 161 release from an input tag in anywhere (#24)
* BAM-161: release from a tag anywhere

* BAM-161: Duplicate clone proto repo step

* BAM-161: fix dir name error

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -2,6 +2,11 @@ name: Build
 
 on:
   workflow_dispatch:
+    inputs:
+      kp_tag:
+        description: 'Optional tag for kp-protocols-clientsdk'
+        required: false
+        default: ''
 
 jobs:
   tagging:
@@ -11,19 +16,23 @@ jobs:
       version: ${{ steps.tag.outputs.version }}
       prerelease: ${{ steps.tag.outputs.prerelease }}
     steps:
-      - name: Fetch head tag from kp-protocols-clientsdk
+      - name: Determine version tag from kp-protocols-clientsdk
         id: tag
         run: |
-          git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
-          cd proto-repo
-          head_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
-          if [[ -z "${head_tag}" ]]; then
+          if [ -n "${{ github.event.inputs.kp_tag }}" ]; then
+             version_tag=${{ github.event.inputs.kp_tag }}
+          else
+            git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+            cd proto-repo
+            version_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
+          fi
+          if [[ -z "${version_tag}" ]]; then
             echo "No tag found on the head commit of kp-protocols-clientsdk repo. Failing the action."
             exit 1
           else
-            echo "tag=${head_tag}" >> $GITHUB_OUTPUT
-            echo "version=${head_tag#v}" >> $GITHUB_OUTPUT
-            if [[ "${head_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
+            echo "tag=${version_tag}" >> $GITHUB_OUTPUT
+            echo "version=${version_tag#v}" >> $GITHUB_OUTPUT
+            if [[ "${version_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
           fi
 
   build-python-3_6:
@@ -42,11 +51,15 @@ jobs:
       - name: Install Requirements
         run: python -m pip install -r versions/3_6/requirements.txt
       - name: Clone Proto Repo
-        run: git clone https://github.com/KodyPay/kp-protocols-clientsdk.git
+        run: |
+          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+          cd proto-repo || { echo "Failed to change directory to proto-repo"; exit 1; }
+          git checkout tags/${{ needs.tagging.outputs.tag }} -b temp-branch || { echo "Failed to checkout tag ${{ needs.tagging.outputs.tag }}"; exit 1; }
+          cd ..
       - name: Move Proto Folder
         run: |
-          cp -R kp-protocols-clientsdk/src/main/proto versions/3_6/proto
-          rm -rf kp-protocols-clientsdk
+          cp -R proto-repo/src/main/proto versions/3_6/proto
+          rm -rf proto-repo
       - name: Generate GRPC Sources
         run: |
           cd versions/3_6
@@ -97,11 +110,15 @@ jobs:
       - name: Install Requirements
         run: python -m pip install -r versions/3_12/requirements.txt
       - name: Clone Proto Repo
-        run: git clone https://github.com/KodyPay/kp-protocols-clientsdk.git
+        run: |
+          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+          cd proto-repo || { echo "Failed to change directory to proto-repo"; exit 1; }
+          git checkout tags/${{ needs.tagging.outputs.tag }} -b temp-branch || { echo "Failed to checkout tag ${{ needs.tagging.outputs.tag }}"; exit 1; }
+          cd ..
       - name: Move Proto Folder
         run: |
-          cp -R kp-protocols-clientsdk/src/main/proto versions/3_12/proto
-          rm -rf kp-protocols-clientsdk
+          cp -R proto-repo/src/main/proto versions/3_12/proto
+          rm -rf proto-repo
       - name: Generate GRPC Sources
         run: |
           cd versions/3_12
