BAM-161: Duplicate clone proto repo step

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -7,6 +7,7 @@ on:
         description: 'Optional tag for kp-protocols-clientsdk'
         required: false
         default: ''
+
 jobs:
   tagging:
     runs-on: ubuntu-latest
@@ -49,8 +50,7 @@ jobs:
         run: python -m pip install --upgrade pip build setuptools wheel
       - name: Install Requirements
         run: python -m pip install -r versions/3_6/requirements.txt
-      - &clone-proto-repo
-        name: Clone Proto Repo
+      - name: Clone Proto Repo
         run: |
           git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
           cd proto-repo || { echo "Failed to change directory to proto-repo"; exit 1; }
@@ -109,7 +109,12 @@ jobs:
         run: python -m pip install twine
       - name: Install Requirements
         run: python -m pip install -r versions/3_12/requirements.txt
-      - *clone-proto-repo
+      - name: Clone Proto Repo
+        run: |
+          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+          cd proto-repo || { echo "Failed to change directory to proto-repo"; exit 1; }
+          git checkout tags/${{ needs.tagging.outputs.tag }} -b temp-branch || { echo "Failed to checkout tag ${{ needs.tagging.outputs.tag }}"; exit 1; }
+          cd ..
       - name: Move Proto Folder
         run: |
           cp -R kp-protocols-clientsdk/src/main/proto versions/3_12/proto
